spring.application.name=paciente-comando-service
server.port=8086

spring.datasource.url=jdbc:postgresql://ep-empty-sea-acdqvx02-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_d1NVfEoInA7g
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.sql.init.mode=always

# Ativa o logging completo para a interface ConvenioClient
logging.level.org.vitacare.pacientecomandoservice.repository.ConvenioClient=DEBUG