services:
  postgres-db:
    image: postgres:15-alpine
    container_name: vitacare-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: vitacare_db
      POSTGRES_USER: vitacare_user
      POSTGRES_PASSWORD: vitacare_password
    volumes:
      - vitacare_postgres_data:/var/lib/postgresql/data


  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      postgres-db:
        condition: service_healthy

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_PASSWORD: ${GIT_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    depends_on:
      service-registry:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "9000:9000"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
      GMAIL_APP_GMAIL: ${VITACARE_GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${VITACARE_GMAIL_APP_PASSWORD}
    depends_on:
      - service-registry
      - config-server
      - postgres-db

  paciente-comando-service:
    build:
      context: .
      dockerfile: paciente-comando-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    depends_on:
      - service-registry
      - config-server
      - postgres-db

volumes:
  vitacare_postgres_data: