spring.application.name=agenda-service
server.port=8085

spring.config.import=configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.org.springframework.security=TRACE

logging.level.org.vitacare.paciente.client.PacienteQueryClient=DEBUG
logging.level.org.vitacare.professional.client.ProfessionalClient=DEBUG

logging.level.org.vitacare.agendamentoservice=DEBUG