spring.application.name=agendamento-service

spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Fallback for local development (override via config server in production)
jwt.secret=yP2dT58Ffit+vWciSR4WP+qsC/y3zXFzu8jgzt2Oagc8VaW0oxCtV8i4Pm41jDPpflT9wL9RUQ0onDW5B6SkeA==

logging.level.org.springframework.security=TRACE

logging.level.org.vitacare.agendamentoservice=DEBUG
