CREATE SCHEMA IF NOT EXISTS emergencia_schema;

CREATE TABLE emergencia_schema.atendimentos_emergencia
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    paciente_id       BIGINT                                  NOT NULL,
    queixas           VARCHAR(255),
    alergias          VARCHAR(255),
    diagnostico       VARCHAR(255),
    prescricao        VARCHAR(255),
    status            VARCHAR(255)                            NOT NULL,
    data_hora_chegada TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_atendimentos_emergencia PRIMARY KEY (id)
);