spring.application.name=patient-service
server.port=8082

spring.datasource.url=jdbc:postgresql://ep-sweet-wind-a8huy3ne-pooler.eastus2.azure.neon.tech:5432/projeto?sslmode=require&channelBinding=require
spring.datasource.username=projeto_owner
spring.datasource.password=npg_Cc4rUNJt0gav
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=public

# -- NÃO MEXER ABAIXO DESTA LINHA --

# 1. Diz para importar a configuração do Config Server
spring.config.import=optional:configserver:

# 2. Habilita a busca do Config Server via Eureka
spring.cloud.config.discovery.enabled=true

# 3. Diz qual é o nome do serviço do Config Server no Eureka
spring.cloud.config.discovery.service-id=config-server

# 4. Informa como encontrar o Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.jpa.hibernate.ddl-auto=update

# --- Configuração de Inicialização de Dados ---
# 'always': Garante que o script 'data.sql' seja sempre executado.
spring.sql.init.mode=always