IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Oncologia')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Oncologia', 'Oncologia é a especialidade médica voltada ao estudo, diagnóstico, tratamento e acompanhamento de pacientes oncológicos. Os oncologistas são responsáveis por identificar diferentes tipos de câncer e desenvolver planos de tratamento personalizados que podem incluir quimioterapia, radioterapia, imunoterapia, terapias direcionadas, cirurgia oncológica, entre outros. A oncologia é dividida em subespecialidades, como oncologia clínica, oncologia cirúrgica, oncologia hematológica e oncologia pediátrica, cada uma com foco em diferentes aspectos e tipos de câncer. O objetivo da oncologia é tratar doenças, melhorar a qualidade de vida dos pacientes e, quando possível, alcançar a cura ou o controle da doença a longo prazo.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Neurologia')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Neurologia', 'A neurologia é a especialidade médica dedicada ao diagnóstico, tratamento e manejo de doenças que afetam o sistema nervoso, que inclui o cérebro, a medula espinhal, os nervos periféricos e os músculos. Os neurologistas tratam uma ampla gama de condições neurológicas, como doenças neurodegenerativas (Alzheimer, Parkinson), distúrbios do movimento, epilepsia, esclerose múltipla, enxaquecas, acidentes vasculares cerebrais (AVC), neuropatias e doenças neuromusculares. A neurologia também abrange o estudo de distúrbios congênitos, infecções do sistema nervoso e lesões traumáticas. O objetivo da neurologia é melhorar a qualidade de vida dos pacientes por meio de tratamentos que aliviem sintomas, controlem doenças e previnam complicações.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Cardiologia')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Cardiologia', 'A Cardiologia é a área da medicina que se concentra no estudo, diagnóstico, prevenção e tratamento das enfermidades relacionadas ao coração e ao sistema circulatório. Os profissionais dessa especialidade, chamados cardiologistas, tratam condições como hipertensão, arritmias, insuficiência cardíaca, doenças das coronárias e valvulopatias, entre outras. Além do tratamento clínico, a cardiologia envolve também técnicas de diagnóstico por imagem, como ecocardiogramas, cateterismos cardíacos e eletrocardiogramas, bem como intervenções minimamente invasivas, como angioplastias e colocação de stents. O principal objetivo é promover a saúde do sistema cardiovascular, prevenir complicações e melhorar a qualidade de vida dos pacientes.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Cirurgia Bariátrica')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Cirurgia Bariátrica', 'Também conhecida como gastroplastia ou "cirurgia de redução do estômago", a cirurgia bariátrica é uma abordagem indicada para tratamento da obesidade e suas comorbidades relacionadas. Ao reduzir o estômago e mexer no intestino, a cirurgia estabelece maior restrição alimentar e um efeito metabólico que ajuda na perda de peso e tratamento de doenças associadas, como o diabetes tipo 2, hipertensão e colesterol alto.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Hematologia')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Hematologia', 'A hematologia é a especialidade médica que trata doenças que se desenvolvem no sangue – como leucemias, linfomas, mielomas, anemia falciforme, tumores germinativos de testículo e ovário, doenças mielodisplásicas e outros quadros –, assim como estuda tratamentos relacionados aos órgãos hematopoéticos, responsáveis por criarem as células que formam o sangue – como a medula óssea, o baço e os linfonodos (gânglios linfáticos). Segundo dados do Instituto Nacional do Câncer (INCA), mais de 10 mil casos são registrados por ano no Brasil envolvendo apenas linfomas.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Oncologia Pediátrica')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Oncologia Pediátrica', 'Oncologia pediátrica é a área da medicina que se concentra no diagnóstico, tratamento e monitoramento de cânceres em crianças e adolescentes. Diferentemente da oncologia voltada para adultos, essa especialidade lida com tipos específicos de câncer que ocorrem com mais frequência em jovens, como leucemias, linfomas, neuroblastomas, tumores cerebrais, tumores ósseos (como osteossarcoma e sarcoma de Ewing), tumores renais (como o tumor de Wilms) e outros tipos de tumores sólidos.Os tratamentos para cânceres em pacientes pediátricos geralmente consistem em uma combinação de quimioterapia, radioterapia, cirurgia e, em certas situações, imunoterapia e transplante de medula óssea. Além de focar na cura da doença, a oncologia pediátrica também se dedica a reduzir os efeitos colaterais a longo prazo que os tratamentos intensivos podem provocar em organismos que ainda estão em desenvolvimento.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Pediatria')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Pediatria', 'A pediatria é a especialidade médica voltada ao cuidado da saúde de bebês, crianças e adolescentes, desde o nascimento até os 19 anos de idade. Ela abrange a prevenção, diagnóstico e tratamento de doenças físicas, mentais e emocionais que afetam essa faixa etária. Os pediatras monitoram o crescimento e o desenvolvimento infantil, administram vacinas, orientam sobre nutrição e segurança, e abordam problemas comportamentais e de desenvolvimento. Além de tratar doenças agudas e crônicas, a pediatria também promove práticas de saúde preventiva para garantir o bem-estar e o desenvolvimento saudável das crianças e adolescentes.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Reumatologia')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Reumatologia', 'A reumatologia é a especialidade médica que se dedica ao diagnóstico, tratamento e acompanhamento de doenças que afetam as articulações, músculos, ossos e tecidos conjuntivos, incluindo doenças autoimunes e inflamatórias. Essas condições, conhecidas como doenças reumatológicas ou reumatismos, podem causar dor, inflamação, rigidez e, em casos graves, deformidades ou comprometimento de funções físicas. Entre as doenças mais comuns tratadas pela reumatologia estão a artrite reumatoide, lúpus, espondilite anquilosante, osteoartrite, fibromialgia, gota e osteoporose. O objetivo da reumatologia é melhorar a qualidade de vida dos pacientes, controlando a dor e prevenindo danos permanentes.');

IF NOT EXISTS (SELECT 1 FROM professionals_service.specialties WHERE name = 'Transplantes')
INSERT INTO professionals_service.specialties (name, description) VALUES ('Transplantes', 'Transplante é um procedimento médico no qual um órgão, tecido ou células de um doador são transferidos para um receptor que possui uma falha ou doença que compromete o funcionamento normal do órgão ou tecido. Esse procedimento pode ser realizado com órgãos como coração, pulmões, fígado, rins e pâncreas, ou com tecidos como pele, córneas, ossos e medula óssea. O transplante visa restaurar a função perdida ou comprometida do órgão ou tecido do receptor, melhorando sua qualidade de vida ou até mesmo salvando sua vida. A compatibilidade entre o doador e o receptor e a prevenção de rejeição pelo sistema imunológico do receptor são fatores críticos no sucesso do transplante.');