CREATE SCHEMA IF NOT EXISTS paciente_comando_schema;

CREATE TABLE pacientes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255),
    data_nascimento date,
    sexo            VARCHAR(255),
    endereco        VARCHAR(255),
    possui_convenio BOOLEAN,
    plano_id        BIGINT,
    cpf             VARCHAR(255),
    CONSTRAINT pk_pacientes PRIMARY KEY (id)
);