# ===================================================================
# TEMPLATE .PROPERTIES PARA NOVOS MICROSERVIÇOS
# ===================================================================
# O desenvolvedor SÓ PRECISA mudar esta linha
spring.application.name=nome-do-servico

# -- NÃO MEXER ABAIXO DESTA LINHA --

# 1. Diz para importar a configuração do Config Server
spring.config.import=optional:configserver:

# 2. Habilita a busca do Config Server via Eureka
spring.cloud.config.discovery.enabled=true

# 3. Diz qual é o nome do serviço do Config Server no Eureka
spring.cloud.config.discovery.service-id=config-server

# 4. Informa como encontrar o Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka